name: Generate terraform docs
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.ref }}

    - name: Render terraform docs inside the README.md and push changes back to PR branch
      uses: terraform-docs/gh-actions@v1.0.0
      with:
        working-dir: modules/alb,modules/ecs,modules/rds,modules/secretsmanager,modules/vpc,modules/terraform-backend-setup,examples/ec2,examples/ec2-dockercompose,examples/ec2-rds,examples/ecs-fargate
        output-file: README.md
        output-method: inject
        git-push: "true"